#!/bin/sh

echo "Installing XCreator, by Skynet Cyberdyne 2022."

# Deps, it could be, there are more to install. You will find out. 
sudo apt-get update
sudo apt-get install -y git g++ cmake build-essential cmake libxmu-dev libxi-dev libgl-dev xorg-dev libglu1-mesa-dev libfreetype6-dev libeigen3-dev libassimp-dev pkg-config mesa-utils freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev libclang-cpp11 libclang1-11 libfreeimage3 libjxr0 libtcl8.6 libtk8.6 tcl tcl8.6 tcl8.6-dev tk tk8.6 tk8.6-dev python3-pip 

python3 -m pip install docwriter
  
cd vendor

# Remove old CMakeCache files. 
# Git recursive clones:
cd glad && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd learnopengl && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd libpng && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd soil && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd zlib && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..

# Included clones:
cd clip-1.5 && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd freetype-2.12.1 && ./configure && ./autogen.sh && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd glew-2.2.0 && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake ./cmake && make -j2 && cd .. && cd .. 
cd glfw-3.3.7 && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd glm && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..

# Install in system dir to avoid link error.
cd freetype-2.12.1 && cd build && sudo make install && cd .. && cd ..

# Build XCreator sample programs.
cd ..
cd XDesignerDialog && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd XDrawOpenGLPrimitives && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd XFileOpenDialog && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd XHorizonalSplitterDialog && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd XSingleButtonDialog && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..
cd XTextEditorDialog && mkdir -p build && cd build && rm -rf CMakeCache.txt && cmake .. && make -j2 && cd .. && cd ..

# Install Opencascade OCCT library. This will ask the user to build the library.
cd OCCT && ./setup && cd ..

echo "Finished Installing XCreator"
